Automated upload of script from bash_skriptimine

diff --git a/praks1/kasutajad_failist b/praks1/kasutajad_failist
--- a/praks1/kasutajad_failist
+++ b/praks1/kasutajad_failist
@@ -1,28 +1,26 @@
 #!/bin/bash
-
-# Kontrollime, kas skripti käivitab root kasutaja
-if [[ $(id -u) -ne 0 ]]; then
-    echo "Ainult root kasutaja saab seda skripti käivitada."
+# Skript loeb kasutajanimed failist ja loob iga kasutaja kasutades lisa_kasutaja.sh skripti
+# Kontrollime, kas sisendfail on antud
+if [ $# -eq 0 ]; then
+    echo "Viga: kasutajate fail on puudu."
+    echo "Kasutamine: $0 <kasutajate_fail>"
     exit 1
 fi
 
-# Kontrollime, kas faili nimi on antud
-if [ -z "$1" ]; then
-    echo "Palun sisesta faili nimi, kust kasutajanimed lugeda."
-    exit 1
+fail="$1"
+
+# Kontrollime, kas fail on loetav
+if [ ! -r "$fail" ]; then
+    echo "Viga: fail '$fail' ei ole loetav."
+    exit 2
 fi
 
-failinimi=$1
-
-# Kontrollime, kas fail eksisteerib
-if [ ! -f "$failinimi" ]; then
-    echo "Faili $failinimi ei leitud."
-    exit 1
-fi
-
-# Loeme kasutajanimed failist ja kutsume iga kasutaja loomiseks eelmist skripti
-while IFS= read -r kasutajanimi; do
-    if [ -n "$kasutajanimi" ]; then
-        ./lisa_kasutaja "$kasutajanimi"
+# Loome kasutajad failist
+while read -r kasutaja; do
+    if [ -n "$kasutaja" ]; then
+        # Käivitame eelmist skripti otse
+        ./lisa_kasutaja "$kasutaja"
+    else
+        echo "Hoiatus: tühi rida vahele jäetud."
     fi
-done < "$failinimi"
+done < "$fail"
diff --git a/praks1/lisa_kasutaja b/praks1/lisa_kasutaja
--- a/praks1/lisa_kasutaja
+++ b/praks1/lisa_kasutaja
@@ -1,61 +1,25 @@
 #!/bin/bash
+# Skript loob kasutaja, määrab kodukataloogi ja seab vaikimisi shelliks Bash
 
-# Kontrollime, kas kasutajanimi on sisestatud
-if [ -z "$1" ]; then
-  echo "Kasutajanimi puudub! Kasutamine: ./lisa_kasutaja <kasutajanimi>"
-  exit 1
+# Kontrollime, kas kasutajanimi on sisendina antud
+if [ $# -eq 0 ]; then
+    echo "Viga: kasutajanimi on puudu."
+    echo "Kasutamine: $0 <kasutajanimi>"
+    exit 1
 fi
 
-# Määrame muutujaks kasutajanime
-KASUTAJANIMI=$1
+kasutajanimi="$1"
 
-# Kontrollime, kas kasutaja juba eksisteerib
-if id "$KASUTAJANIMI" &>/dev/null; then
-  echo "Kasutaja '$KASUTAJANIMI' juba eksisteerib!"
-  exit 1
-fi
-
-# Küsime ja määrame kasutajale parooli
-echo "Sisesta parool kasutajale '$KASUTAJANIMI':"
-read -s PAROOL1
-echo "Sisesta parool uuesti:"
-read -s PAROOL2
-
-# Kontrollime, kas paroolid kattuvad
-if [ "$PAROOL1" != "$PAROOL2" ]; then
-  echo "Paroolid ei kattu. Proovi uuesti."
-  exit 1
-fi
-
-# Loome kasutaja koos kodukataloogiga ja määrame vaikimisi shelliks /bin/bash
-sudo useradd -m -d /home/$KASUTAJANIMI -s /bin/bash $KASUTAJANIMI
+# Loome kasutaja, määrame kodukataloogi ja vaikimisi shelliks Bash
+useradd -m -d "/home/$kasutajanimi" -s /bin/bash "$kasutajanimi"
 
 # Kontrollime, kas kasutaja loodi edukalt
 if [ $? -eq 0 ]; then
-  echo "Kasutaja '$KASUTAJANIMI' loodi edukalt."
+    echo "Kasutaja '$kasutajanimi' on edukalt loodud koos Bash shelliga."
 else
-  echo "Kasutaja loomine ebaõnnestus."
-  exit 1
+    echo "Kasutaja '$kasutajanimi' loomine ebaõnnestus."
+    exit 2
 fi
 
-# Määrame kasutajale parooli
-echo "$KASUTAJANIMI:$PAROOL1" | sudo chpasswd
-
-# Kontrollime, kas parool määrati edukalt
-if [ $? -eq 0 ]; then
-  echo "Parool määrati edukalt."
-else
-  echo "Parooli määramine ebaõnnestus."
-  exit 1
-fi
-
-# Loome vajalikud peidetud failid kasutaja kodukataloogi
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.bashrc
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.profile
-sudo -u $KASUTAJANIMI touch /home/$KASUTAJANIMI/.bash_logout
-
-# Kontrollime loodud kodukataloogi ja failide struktuuri
-echo "Kontrollime loodud kodukataloogi:"
-ls -la /home/$KASUTAJANIMI
-
-echo "Kasutaja '$KASUTAJANIMI' on edukalt loodud koos vajalike peidetud failidega!"
+# Kontrollime, kas kodukataloogis on vajalikud peidetud failid
+ls -a "/home/$kasutajanimi"
